version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - network2
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend2
    restart: always
    environment:
      - BACKEND_PORT=5000
      - DB_HOST=mysql
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=tasks_db
    ports:
      - "5001:5000"
    networks:
      - network2
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: frontend2
    restart: always
    environment:
      - REACT_APP_API_URL=http://backend:5001
    ports:
      - "3001:80"
    networks:
      - network2
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  network2:   # <---- Aquí defines la red correctamente
